spring.application.name=proxora

spring.datasource.url=${DB_URL}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

app.admin.correo=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
